const ACTIONS = Object.freeze({
  LOAD_COCKTAILS: 'LOAD_COCKTAILS',
  LOAD_COCKTAIL: 'LOAD_COCKTAIL',
  FILTERED_COCKTAILS: 'FILTERED_COCKTAILS',
  NO_RESPONSE_RECEIVED: 'NO_RESPONSE_RECEIVED',
  CLEAR_PREVIOUS_COCKTAIL: 'CLEAR_PREVIOUS_COCKTAIL',
});

export default ACTIONS;
